### ISSUE TITLE
https://storitve.ujp.gov.si/dostop/preverjanje-strukture/ kontrola .xml

### ISSUE THREAD

**Issue by LukaMesec** [Media24si/eslog2#1]
Kontrola generiranjega .xml (https://storitve.ujp.gov.si/dostop/preverjanje-strukture/) javlja sledeče: "TIP	OPIS
Napaka	Dokument ne ustreza predpisani shemi eSlog 1.6 oziroma eSlog 2.0. Napaka v vrstici 247 in stolpcu 14! (Ime vozlišča: D_1230, tip vozlišča: Element, opis: The 'urn:eslog:2.00:D_1230' element is invalid - The value '' is invalid according to its datatype 'urn:eslog:2.00:string1..35' - The actual length is less than the MinLength value.)"

(To se zgodi tudi pri uvozu inv.xml). To vozlišče povzroča težave tudi ob uvozu v spletno banko.

**Comment by Neoglyph** [comment]
Živijo, 

Brez konkretnega primera dokumenta lahko govorim samo na pamet. 

Napaka izhaja iz praznega polja oz. vozlišča  `D_1230` bodisi pri dodajanju popusta na račun ali postavko.

Vozlišča so sledeča 

```
BT-104 
Document level charge reason
The reason for the document level charge, expressed as text.
/Invoice/M_INVOIC/G_SG16[S_ALC/D_5463='C']/S_ALC/C_C552/D_1230
```

```
BT-144
Invoice line charge reason
The reason for the Invoice line charge, expressed as text.
/Invoice/M_INVOIC/G_SG26/G_SG39[S_ALC/D_5463='C']/S_ALC/C_C552/D_1230
```

Pri dodajanju popustov dodajte zraven še razlog popusta (npr. "Popust", "Akcijski popust", "Prodajni popust") s pomočjo `setReason` metode na `InvoiceDiscount` ali `InvoiceItemDiscount`. To bi moralo odpraviti problem validacije.

Primer rešitve: 


```php
// Invoice item 
$invoiceItem = (new \Media24si\eSlog2\InvoiceItem())
    ->setRowNumber($key + 1)
    ->setName($item->title)
    ->setDescription($desc)
    ...
    ;
   
// Adding discount - Be sure to add a reason for the discount (can be the name of the discount)                  
foreach ($discountsOnItem as $discount) {
    $invoiceItem->addItemAllowance(
        (new InvoiceItemDiscount())
            ->setReason($discount->title) // "Akcijski popust", "Popust"
            ->setReasonCode(95)
            ->setPercentage($discount->percentage)
            ...
            ;
    );
}
```

Postopek je enak pri dodajanju popusta na dokument 

```php
// Invoice
$eInvoice = (new \Media24si\eSlog2\Invoice())
    ->setSeller($seller)
    ->setBuyer($buyer)
    ...
    ;

// Rest of the code ...

// Adding discount - Be sure to add a reason for the discount (can be the name of the discount) 
foreach ($documentLevelDiscounts as $discount) {
    $eInvoice->addDocumentAllowance(
        (new \Media24si\eSlog2\InvoiceDiscount())
            ->setReason($discount->title) // "Akcijski popust", "Popust"
            ->setReasonCode(95)
            ->setPercentage($discount->percentage)
            ...
            ;
    );
}
```

**Comment by LukaMesec** [comment]
->setReason() reši problem z validacijo,  v `tests/InvoiceTest.php` bi bilo smiselno dodati tudi to metodo..., hvala in lp
